class WithdrawalError(Exception):
  pass

class NewRoundError(Exception):
  pass